### ISSUE TITLE
Generating images for the tilesets

### ISSUE THREAD

**Issue by shr-sys** [dimsemenov/photoswipe-deep-zoom-plugin#3]
I am really trying to make this plugin work for my use case, but the part which I'm unable to understand is how to generate these images like you have done in the demo image folder. I just have one single image that i wish to enable deep zoom features on and pass your plugin as a prop through react-photoswipe component, is it possible to explain how do i go about doing that ?

**Comment by dimsemenov** [comment]
You'll need to generate tiles in Deepzoom or Zoomify format via some server-side tool. There are multiple of them, personally, I used vips https://www.libvips.org/API/current/Making-image-pyramids.html

**Comment by shr-sys** [comment]
Thank you so much, i will use this the next time ! I went down a rabbit hole and used a very old tool 'Deep zoom composer' worked out for me. Thank you for the resource ! I had one more concern, while using the npm package for the plugin i seem to get an error while importing(inside react).
 
![image](https://user-images.githubusercontent.com/117628450/204091068-92b1923f-6524-41d0-8abe-163893a3c811.png)

**Comment by dimsemenov** [comment]
The deep zoom plugin is not a TypeScript component, you can check guides like https://medium.com/@steveruiz/using-a-javascript-library-without-type-declarations-in-a-typescript-project-3643490015f3

**Comment by shr-sys** [comment]
I am currently not using typescript in any of my projects, this is just plain create react app 🤔

**Comment by shr-sys** [comment]
![image](https://user-images.githubusercontent.com/117628450/204735960-65797b2f-e68b-44b9-951c-9a4bc688ab01.png)

I ran your exact repo in my dev environment with my own image set (generated via the tool you recommened), but upon zooming iam getting this white patch on one corner of the zoomed in variant.

Using the same image set in openseadragon the zoomed in variant is slightly whiter compared to the parent image (just like the white patch in deepzoom plugin).

Only a small patch is white while using your plugin, but using openseadragon the entire image is rendered in white.

is this something that you can assist with in regards to the image processing tool you recommended ? any help would be appreciated and thanks for the overall help provided.

**Comment by shr-sys** [comment]
Hi sorry thank you for your time, the issue was resolved it was a problem with the image color format (CYMK). Had to convert it into RGB for vips to render exact image. Closing the issue now !
